apiVersion: v1
kind: Service
metadata:
  name: svc-redis-cluster
  labels:
    name: svc-redis-cluster
spec:
  ports:
  - port: 6379
    targetPort: 6379
  clusterIP: None
  selector:
    name: sts-redis-cluster
