apiVersion: v1
kind: Service
metadata:
  name: svc-redis-cluster-np
  labels:
    name: svc-redis-cluster-np
spec:
  ports:
  - port: 6379
    targetPort: 6379
    nodePort: 6379
  type: NodePort
  selector:
    name: sts-redis-cluster
